[[formato-asciidoc]]
= O formato AsciiDoc

Mundialmente aceito e difundido na produção de documentos, como artigos, manuais, apresentações, livros, etc, o {uri-asciidoc}[formato AsciiDoc] é muito útil para a **produção ágil e colaborativa de documentos**. Por ser um formato escrito em texto puro, contendo marcações para representar coisas como títulos, listas, figuras, links, etc, quaisquer alterações realizadas num documento que tenha esse formato pode ser visualizada por um número sem fim de ferramentas que possibilitam comparar a diferença entre dois textos.

Qualquer editor de texto simples pode ser utilizado para editar documentos no formato AsciiDoc. Dessa forma, eles é bastante expressivo na agilidade de escrita pois possibilita os autores utilizarem suas ferramentas preferidas para edição, sejam elas quais forem. Além disso, esse formato possibilita os autores abstrairem-se de detalhes exaustivos sobre a forma como o texto será apresentado fazendo-os focar, apenas, no conteúdo e em marcações estruturais do documento.

Documentos em AsciiDoc podem ser fracionados para ter uma edição mais focada. Isso significa que um grande documento pode ser dividido em sessões que são agrupadas, no final, para a geração de um documento completo. Claramente, esse recurso facilita a edição colaborativa. Essa pode ser realizada através do compartilhamento do documento em alguma ferramenta de controle de versões como, por exemplo, o {uri-git}[Git].

Um documento AsciiDoc podem conter gráficos, imagens, vídeos (útil para geração no formato {uri-epub}[EPUB]), {uri-mathjax}[MathJax], {uri-asciimath}[AsciiMath], {uri-tex-latex}[Tex/LaTex], http://epsilon.my.noteshare.io/section/chemistry-jc[fórmulas químicas], etc. Além disso é possível compor um documento AsciiDoc inserindo, dentro dele, linhas específicas de outros arquivos (por exemplo, código fonte).

O formato AsciiDoc pode ser facilmente apresentado e convertido para outros formatos, como {uri-docbook}[DocBook], HTML, PDF, EPUB e {uri-kf8-mobi}[KF8/MOBI]. No caso da conversão para HTML, essa tarefa pode, até mesmo, ser realizada por browsers através da <<visualizacao-em-browsers,instalação de plugins>>.

O {uri-github}[GitHub], um gerenciador de repositórios Git, reconhece o formato AsciiDoc e gera, automaticamente, versões HTML para documentos nesse formato. O {uri-gitlab}[GitLab], outro gerenciador, possui https://gitlab.com/gitlab-org/gitlab-ce/issues/10778[uma issues aberta] para que também sejam realizadas integrações com o formato. Espera-se que, em breve, vários outros gerenciadores de repositórios, como {uri-bitbucket}[BitBucket], {uri-tfs}[TFS], etc, também estejam interpretando este formato tão bem quanto já o fazem para o formato {uri-markdown}[Markdown].

A melhor forma de aprender sobre o formato AsciiDoc é ler seus manuais e, obviamente, começar a editar os documentos deste repositório seguindo a estrutura e a sintaxe já existente nesses documentos. Segue uma lista de links úteis para o aprendizado do formato AsciiDoc:

* http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference]
* http://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer’s Guide]
* http://asciidoctor.org/docs/asciidoc-recommended-practices/[AsciiDoc Recommended Practices]

Também é muito importante a leitura do http://asciidoctor.org/docs/user-manual/["Asciidoctor User Manual"] e existe, ainda, o livro {uri-asciidoctor-notebook}["Awesome Asciidoctor Notebook"], gratuito, para você se aprofundar ainda mais.
